#index:
#    path: /
#    controller: App\Controller\DefaultController::index
product_list:
    path: /api/v1/products
    controller: App\Controller\ProductController::indexAction
    methods: [GET]

product_create:
    path: /api/v1/products
    controller: App\Controller\ProductController::createAction
    methods: [POST]
